/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Editer;
import java.awt.Window;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JComponent;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import models.*;

/**
 *
 * @author sz_21
 */
public class Form extends javax.swing.JPanel {

    Editer editer = new Editer();
    
    private int userID;
    private boolean isCreate;
    private StoryType st = null;
    private Stories s = null;
    private ArrayList<StoryType> globalStoryTypeList = new ArrayList();
    private ArrayList<Stories> globalStoryList = new ArrayList();
    
    private static final SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
    
    public Form(int userID,boolean isCreate, boolean isEdit,boolean isSearch) {
        initComponents();
        fillStoryTypeList();
        paneNewStoryType.setVisible(false);
        this.userID=userID;
        this.isCreate=isCreate;
        
        if (isCreate){
            storyPane.setVisible(false);
            edit.setVisible(false);
        }
        
        if (isEdit){
            storyPane.setVisible(true);
            edit.setVisible(true);
            saveStory.setVisible(false);
            fillUserStoriesList();
        }
        
        if (isSearch){
            storyPane.setVisible(true);
            edit.setVisible(false);
            saveStory.setVisible(false);
            newStoryType.setVisible(false);
            fillAllStoriesList();
            this.storyTypeComboBox.setEnabled(false);
            this.title.setEnabled(false);
            this.shortDescrip.setEnabled(false);
            this.story.setEnabled(false);
        }
    }
    
    private void fillStoryTypeList(){
        this.globalStoryTypeList = this.editer.getStoryTypeList();
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        
        int count = 0;
        for(StoryType st : this.globalStoryTypeList){
            model.addElement(st.getName());
            count++;
        }
        
        this.storyTypeComboBox.setModel( model );   
    }
    
    private void fillAllStoriesList(){
        this.globalStoryList = this.editer.getAllStoriesList();
        DefaultListModel model = new DefaultListModel();
        
        int count = 0;
        for(Stories s : this.globalStoryList){
            model.add(count, s.getTitle() );
            count++;
        }
        
        this.storyList.setModel( model );
    }
    
    private void fillUserStoriesList(){
        this.globalStoryList = this.editer.getUserStoriesList(userID);
        DefaultListModel model = new DefaultListModel();
        
        int count = 0;
        for(Stories s : this.globalStoryList){
            model.add(count, s.getTitle() );
            count++;
        }
        
        this.storyList.setModel( model );
        this.title.getText();
        this.shortDescrip.getText();
        this.story.getText();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        storyPane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        storyList = new javax.swing.JList<>();
        formPane = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        title = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        storyTypeComboBox = new javax.swing.JComboBox<>();
        newStoryType = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        shortDescrip = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        story = new javax.swing.JTextArea();
        edit = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        paneNewStoryType = new javax.swing.JPanel();
        newStoryTypeName = new javax.swing.JTextField();
        newStoryT = new javax.swing.JButton();
        saveStory = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(550, 450));

        jLabel1.setText("Historias:");

        storyList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        storyList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                storyListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(storyList);

        javax.swing.GroupLayout storyPaneLayout = new javax.swing.GroupLayout(storyPane);
        storyPane.setLayout(storyPaneLayout);
        storyPaneLayout.setHorizontalGroup(
            storyPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(storyPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(storyPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(storyPaneLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 35, Short.MAX_VALUE)))
                .addContainerGap())
        );
        storyPaneLayout.setVerticalGroup(
            storyPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(storyPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Titulo:");

        jLabel3.setText("Tipo De Historia:");

        storyTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        storyTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storyTypeComboBoxActionPerformed(evt);
            }
        });

        newStoryType.setText("Nuevo Tipo");
        newStoryType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newStoryTypeActionPerformed(evt);
            }
        });

        jLabel4.setText("Descripcion Corta:");

        shortDescrip.setColumns(20);
        shortDescrip.setRows(5);
        jScrollPane2.setViewportView(shortDescrip);

        jLabel5.setText("Historia:");

        story.setColumns(20);
        story.setRows(5);
        jScrollPane3.setViewportView(story);

        edit.setText("Guardar");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        exit.setText("Salir");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        newStoryTypeName.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        newStoryT.setText("Crear");
        newStoryT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newStoryTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneNewStoryTypeLayout = new javax.swing.GroupLayout(paneNewStoryType);
        paneNewStoryType.setLayout(paneNewStoryTypeLayout);
        paneNewStoryTypeLayout.setHorizontalGroup(
            paneNewStoryTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneNewStoryTypeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newStoryTypeName)
                .addContainerGap())
            .addGroup(paneNewStoryTypeLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(newStoryT)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        paneNewStoryTypeLayout.setVerticalGroup(
            paneNewStoryTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneNewStoryTypeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newStoryTypeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(newStoryT))
        );

        saveStory.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        saveStory.setText("Guardar");
        saveStory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveStoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formPaneLayout = new javax.swing.GroupLayout(formPane);
        formPane.setLayout(formPaneLayout);
        formPaneLayout.setHorizontalGroup(
            formPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formPaneLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formPaneLayout.createSequentialGroup()
                        .addGroup(formPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formPaneLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(formPaneLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(storyTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(newStoryType)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(paneNewStoryType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(formPaneLayout.createSequentialGroup()
                            .addComponent(saveStory)
                            .addGap(18, 18, 18)
                            .addComponent(edit)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(exit))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, formPaneLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        formPaneLayout.setVerticalGroup(
            formPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(formPaneLayout.createSequentialGroup()
                        .addGroup(formPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(formPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(storyTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newStoryType)))
                    .addComponent(paneNewStoryType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(formPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formPaneLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel5))
                    .addGroup(formPaneLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(edit)
                        .addComponent(exit))
                    .addComponent(saveStory))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(storyPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(formPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(storyPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void newStoryTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newStoryTypeActionPerformed
        paneNewStoryType.setVisible(true);
        
    }//GEN-LAST:event_newStoryTypeActionPerformed

    private void newStoryTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newStoryTActionPerformed
        String name = this.newStoryTypeName.getText();
        try{
            editer.saveStoryType(null, name);
            JOptionPane.showMessageDialog(this, "Se guardo correctamente.");
            fillStoryTypeList();
            paneNewStoryType.setVisible(false);
        } catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage() );
        }
    }//GEN-LAST:event_newStoryTActionPerformed

    private void storyTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storyTypeComboBoxActionPerformed
        paneNewStoryType.setVisible(false);
    }//GEN-LAST:event_storyTypeComboBoxActionPerformed

    private void saveStoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveStoryActionPerformed
        int stIndex= storyTypeComboBox.getSelectedIndex();
        this.st=this.globalStoryTypeList.get(stIndex);
        int stId=st.getId();
        String titleStory = this.title.getText();
        String shortDescription = this.shortDescrip.getText();
        String compleateStory = this.story.getText();
        Timestamp timestamp = new Timestamp(System.currentTimeMillis());
        String timeS=date.format(timestamp);
        try{
            editer.saveStory(null, userID, stId, titleStory, shortDescription, compleateStory, timeS);
            JOptionPane.showMessageDialog(this, "Se guardo correctamente.");
            JComponent component = (JComponent) evt.getSource();
            Window win = SwingUtilities.getWindowAncestor( component );
            win.dispose();
            
        } catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage() );
        }
    }//GEN-LAST:event_saveStoryActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        JComponent component = (JComponent) evt.getSource();
        Window win = SwingUtilities.getWindowAncestor( component );
        win.dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        int sIndex=storyList.getSelectedIndex();
        this.s = this.globalStoryList.get(sIndex);
        
        int stIndex= storyTypeComboBox.getSelectedIndex();
        this.st=this.globalStoryTypeList.get(stIndex);
        int stId=st.getId();
        
        String titleStory = this.title.getText();
        String shortDescription = this.shortDescrip.getText();
        String compleateStory = this.story.getText();
        Timestamp timestamp = new Timestamp(System.currentTimeMillis());
        String timeS=date.format(timestamp);
        try{
            editer.saveStory(s.getId(), userID, stId, titleStory, shortDescription, compleateStory, timeS);
            JOptionPane.showMessageDialog(this, "Se guardo correctamente.");
            JComponent component = (JComponent) evt.getSource();
            Window win = SwingUtilities.getWindowAncestor( component );
            win.dispose();
            
        } catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage() );
        }
    }//GEN-LAST:event_editActionPerformed

    private void storyListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_storyListMouseClicked
        JList target = (JList) evt.getSource();
        int index = target.locationToIndex( evt.getPoint() );
        this.s = this.globalStoryList.get(index);
        
        int stIndex= s.getStoryTypeID() - 1;
        storyTypeComboBox.setSelectedIndex(stIndex);
        
        this.title.setText(s.getTitle());
        this.shortDescrip.setText(s.getShortDescription());
        this.story.setText(s.getStory());
    }//GEN-LAST:event_storyListMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton edit;
    private javax.swing.JButton exit;
    private javax.swing.JPanel formPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton newStoryT;
    private javax.swing.JButton newStoryType;
    private javax.swing.JTextField newStoryTypeName;
    private javax.swing.JPanel paneNewStoryType;
    private javax.swing.JButton saveStory;
    private javax.swing.JTextArea shortDescrip;
    private javax.swing.JTextArea story;
    private javax.swing.JList<String> storyList;
    private javax.swing.JPanel storyPane;
    private javax.swing.JComboBox<String> storyTypeComboBox;
    private javax.swing.JTextField title;
    // End of variables declaration//GEN-END:variables
}
